[project]
name = "hanyuu"
version = "1.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.7",
    "sqlalchemy[aiosqlite,asyncio]>=2.0.36",
    "greenlet>=3.1.1",
    "pydantic-settings>=2.6.1",
    "fastapi[standard]>=0.115.5",
    "asyncpg>=0.30.0",
    "orjson>=3.10.12",
    "rapidfuzz>=3.10.1",
    "filelock>=3.16.1",
    "aiofiles>=24.1.0",
    "pyquery>=2.0.1",
    "ffmpeg-python>=0.2.0",
    "yt-dlp>=2024.12.23",
    "httpx<0.28.0",
    "qbittorrent-api>=2024.12.71",
    "bencodepy>=0.9.5",
    "anime-utils",
    "alembic>=1.17.2",
    "cachetools>=6.2.4",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "termcolor>=2.5.0",
    "ruff>=0.14.4",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "B",
    "Q",
    "I",
    "RUF",
    "FAST",
]

[tool.uv.sources]
anime-utils = { git = "https://github.com/mozhaa/anime-utils.git", rev = "v1.2.5" }

[tool.ruff]
line-length = 120

[tool.alembic]
output_encoding = "utf-8"
path_separator = "os"
script_location = "%(here)s/alembic"
file_template = "%%(year)d_%%(month).2d_%%(day).2d_%%(slug)s"
prepend_sys_path = [
    "."
]

[[tool.alembic.post_write_hooks]]
entrypoint = "ruff_format"
executable = "ruff"
name = "ruff_format"
options = "format REVISION_SCRIPT_FILENAME"
type = "exec"

[[tool.alembic.post_write_hooks]]
entrypoint = "ruff_check"
executable = "ruff"
name = "ruff_check"
options = "check --fix REVISION_SCRIPT_FILENAME"
type = "exec"
