"""empty message

Revision ID: f9f3e6ee4c15
Revises: 9350dda64626
Create Date: 2026-01-10 18:04:22.138511

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9f3e6ee4c15"
down_revision: Union[str, Sequence[str], None] = "9350dda64626"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("qitem_source", sa.Column("dl_info", sa.String(), nullable=True))
    op.drop_column("qitem_source", "downloading")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("qitem_source", sa.Column("downloading", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("qitem_source", "dl_info")
    # ### end Alembic commands ###
